[package]
name = "hecate"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
thiserror = "1.0.61"
hecate_driver = { path = "compiler/hecate_driver"}

[workspace]
members = [
    "compiler/hecate_driver"
]